services:
  postgres:
    image: postgres:16
    container_name: solorecord-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: solorecord_db
      POSTGRES_USER: solorecord
      POSTGRES_PASSWORD: solorecord_pass
    ports:
      - "5432:5432"
    volumes:
      - solorecord_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2.6-alpine
    container_name: solorecord-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  solorecord_pgdata: